version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    command:
      - '-c'
      - 'shared_buffers=256MB'
      - '-c'
      - 'max_connections=200'
    environment:
      POSTGRES_DB: book_shelf
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - db_network
networks:
  db_network:
    external: true

volumes:
  postgresql_data: